version: '3.7'

services:
  localstack:
    container_name: localstack_repro
    image: localstack/localstack:0.10.6
    ports:
      - "4572:4572"
      - "8080:8080"
    environment:
      - SERVICES=s3:4572
      - DEFAULT_REGION=ap-northeast-1
      - PORT_WEB_UI=8080
      - USE_SSL=false
      - DEBUG=true
